[package]
name = "october"
version = "0.1.1"
entrypoint = "template.typ"
authors = ["Pierre Marshall <pierre.marshall@gmail.com>"]
license = "MIT-0"
description = "Simple printable year calendar"
repository = "https://github.com/extua/october"
categories = ["office"]
keywords = ["calendar", "monthly", "schedule"]
exclude = ["*.pdf"]
compiler = "0.11.1"

[template]
path = "template"
entrypoint = "calendar.typ"
thumbnail = "thumbnail.png"
